### ISSUE TITLE
Frequent crashes with sniffer

### ISSUE THREAD

**Issue by 1rabbit** [jmc265/node-red-contrib-rpi-433#9]
Every time there's a high rate of messages received i get this issue :
(RPI4)

```
Node-RED[21655]: 5 Nov 17:33:11 - [red] Uncaught Exception:
Node-RED[21655]: 5 Nov 17:33:11 - SyntaxError: Unexpected token { in JSON at position 37
Node-RED[21655]:     at JSON.parse (<anonymous>)
Node-RED[21655]:     at Sniffer.onData (/home/pi/.node-red/node_modules/rpi-433-v3/Sniffer.js:61:26)
Node-RED[21655]:     at Socket.<anonymous> (/home/pi/.node-red/node_modules/underscore/underscore-node-f.cjs:1158:36)
Node-RED[21655]:     at Socket.<anonymous> (/home/pi/.node-red/node_modules/underscore/underscore-node-f.cjs:67:27)
Node-RED[21655]:     at Socket.emit (events.js:314:20)
Node-RED[21655]:     at addChunk (_stream_readable.js:297:12)
Node-RED[21655]:     at readableAddChunk (_stream_readable.js:272:9)
Node-RED[21655]:     at Socket.Readable.push (_stream_readable.js:213:10)
Node-RED[21655]:     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
systemd[1]: nodered.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: nodered.service: Failed with result 'exit-code'.
```

**Comment by Esprim0** [comment]
Same here:

```
SyntaxError: Unexpected token { in JSON at position 35
    at JSON.parse (<anonymous>)
    at Sniffer.onData (/home/pi/.node-red/node_modules/rpi-433-v3/Sniffer.js:61:26)
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/underscore/modules/debounce.js:21:34)
    at Socket.<anonymous> (/home/pi/.node-red/node_modules/underscore/modules/restArguments.js:16:27)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:199:23)
```

Any different solution to get 433 mhz emitter working on node-red & raspberry pi 4?

**Comment by jmc265** [comment]
Hi. Could you help me debug this as I can't reproduce due to no longer using this package myself?
Please do the following:

1. Edit file /home/pi/.node-red/node_modules/rpi-433-v3/Sniffer.js
2. On line 60 add this: `console.log("Buffer output:", buffer);`
3. Save file and restart node-red
4. Reproduce the error
5. Paste the contents of the debug log of node-red into this issue

Many thanks
